{% set version = "2.2.2-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-runjags
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/runjags_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/runjags/runjags_{{ version }}.tar.gz
  sha256: 6f656e4d0620c0806e596ddb4bfec3934534ec17c02da699fcbfd6720a6f424f

build:
  number: 1
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-coda >=0.17_1
    - r-lattice >=0.20_10
    - jags

  run:
    - r-base
    - r-coda >=0.17_1
    - r-lattice >=0.20_10
    - jags

test:
  commands:
    - $R -e "library('runjags')"           # [not win]
    - "\"%R%\" -e \"library('runjags')\""  # [win]

about:
  home: https://github.com/ku-awdc/runjags

  license: GPL-2.0-only
  summary: User-friendly interface utilities for MCMC models via Just Another Gibbs Sampler (JAGS), facilitating the use of parallel (or distributed) processors for multiple chains, automated control of convergence and sample length diagnostics, and evaluation of the performance of a model using drop-k validation or against
    simulated data. Template model specifications can be generated using a standard lme4-style formula interface to assist users less familiar with the BUGS syntax.  A JAGS extension module provides additional distributions including the Pareto family of distributions, the DuMouchel prior and the half-Cauchy prior.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
